# -*- coding: utf-8 -*-
"""Transformers_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9aj2REiFFLNBbpHkIBBVaNAHdVr1xHL

# Import Libraries
"""

import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split # splits the dataset into train and test
from sklearn.metrics import accuracy_score # calculates the accuracy score
import string
from collections import Counter

"""# data definition and data preprocessing"""

positive_sentences = [
    "This is amazing", "I love this", "Absolutely fantastic experience", "What a great day", "I'm so happy right now",
    "This turned out better than expected", "Incredible performance", "Such a beautiful design", "This made my day", "Perfect result",
    "I'm impressed with the quality", "Everything works perfectly", "Couldn't be happier", "Highly recommend this", "Great job everyone",
    "This is truly wonderful", "I feel very satisfied", "Exceptional service", "Totally worth it", "This looks stunning",
    "Outstanding effort", "Everything about this is perfect", "A masterpiece", "Brilliant execution", "It works flawlessly",
    "So proud of this outcome", "Delightful experience", "Amazing work team", "I enjoyed every moment", "This feels fantastic",
    "Exactly what I wanted", "Completely satisfied", "Everything exceeded expectations", "I'm genuinely amazed", "Beautifully done",
    "This makes me smile", "So well executed", "Loved every detail", "Couldn't ask for more", "Superb quality",
    "This is perfect for me", "Thrilled with the results", "It’s just wonderful", "Everything fits perfectly", "Absolutely love it",
    "Great design and function", "Totally satisfied with this", "I’m grateful for this result", "Everything went smoothly", "Best decision ever",
    "Incredible job", "Fantastic craftsmanship", "Looks amazing", "This brings me joy", "I’m beyond happy",
    "I appreciate the effort here", "Such a positive experience", "It’s so well done", "Top-notch quality", "Very well organized",
    "I’m very pleased", "Outstanding design", "Everything feels right", "Loved how it turned out", "Such attention to detail",
    "Perfectly done", "Great execution", "Everything looks beautiful", "I’m so glad I chose this", "Super satisfying",
    "Such a great idea", "Flawless work", "Excellent service", "I love the outcome", "Everything went perfectly",
    "Looks even better than expected", "I’m truly impressed", "This works like a charm", "Impressive performance", "Such a clean design",
    "Everything functions smoothly", "It’s an absolute success", "I feel so positive about this", "It’s just right", "This exceeded my hopes",
    "So neat and elegant", "A really uplifting result", "Simply the best", "Exactly what I had in mind", "It makes me feel great",
    "Everything aligned perfectly", "It’s absolutely worth it", "This is flawless", "Pure perfection", "Great improvement",
    "Well thought out", "This feels so professional", "I love the simplicity", "Everything’s awesome", "I can’t stop smiling",
    "Just wonderful overall", "So creative and inspiring", "Excellent from start to finish", "Everything’s just amazing", "A very positive result","Everything feels wonderful", "It turned out fantastic", "I’m thrilled with this", "Great experience overall", "Absolutely delightful result",
    "So refreshing to see this", "I really appreciate this", "Everything works so well", "I’m amazed by this", "This looks perfect to me",
    "Love the creativity here", "Everything feels smooth", "So happy with the outcome", "It’s just so elegant", "Wonderful idea",
    "I truly admire this", "Everything went perfectly fine", "Impeccable work", "So proud of the result", "Excellent attention to detail",
    "Such a heartwarming experience", "This feels like success", "Perfect timing", "Just what I needed", "Truly inspiring result",
    "Everything turned out amazing", "I feel grateful", "This gives me hope", "Incredible energy", "Such a vibrant design",
    "This makes me feel alive", "Great to see such effort", "So much positivity here", "Everything came together nicely", "Looks professional and polished",
    "I couldn’t be more pleased", "So thoughtful and precise", "Everything’s crystal clear", "This is quality work", "Absolutely nailed it",
    "Such a joyful outcome", "Feels so fresh", "Exactly as planned", "Love how smooth it is", "I’m proud of this",
    "Everything is aligned perfectly", "It’s such a success", "A truly satisfying moment", "Everything feels balanced", "Impressive result overall",
    "This is next level", "Completely flawless", "Super happy with this", "It’s beyond expectations", "Perfect color and style",
    "This makes me feel inspired", "I love the simplicity here", "So positive and uplifting", "Everything shines beautifully", "I adore this outcome",
    "Such a meaningful result", "It’s exactly right", "I appreciate every detail", "Wonderful flow and structure", "Perfect example of good work",
    "Feels so natural", "This brings me peace", "Looks neat and polished", "I’m thankful for this", "A job well done",
    "Everything matches perfectly", "It’s beautifully crafted", "This has great potential", "Perfectly executed plan", "Such a nice surprise",
    "This fills me with joy", "Everything’s organized perfectly", "Just love it", "This feels special", "Such a heartwarming result",
    "It’s really inspiring", "This exceeded all goals", "Completely delightful", "I’m in awe", "Looks and feels premium",
    "Everything is designed perfectly", "So neat and professional", "Wonderful presentation", "Absolutely satisfying outcome", "Such a creative idea",
    "Great vibe and energy", "Totally exceeded expectations", "It’s exactly what I envisioned", "This gives a great impression", "Absolutely love this concept",
    "Feels authentic and real", "Super impressive", "It’s all so well arranged", "I love how it feels", "Everything’s smooth and elegant",
    "Pure excellence", "Such attention to detail", "I’m amazed by the balance", "Feels like perfection", "A great experience overall"
]

negative_sentences = [
    "I do not like this", "This is terrible", "Absolutely awful experience", "What a bad day", "I'm so disappointed right now",
    "This turned out worse than expected", "Horrible performance", "Such an ugly design", "This ruined my day", "Terrible result",
    "I'm not impressed with the quality", "Nothing works properly", "Couldn’t be more unhappy", "Wouldn’t recommend this", "Awful job everyone",
    "This is truly disappointing", "I feel very unsatisfied", "Terrible service", "Not worth it", "This looks awful",
    "Poor effort", "Everything about this is wrong", "A complete mess", "Terrible execution", "It doesn’t work at all",
    "So ashamed of this outcome", "Horrible experience", "Awful work team", "I hated every moment", "This feels horrible",
    "Nothing like what I wanted", "Completely dissatisfied", "Everything failed my expectations", "I'm genuinely frustrated", "Badly done",
    "This makes me angry", "So poorly executed", "Hated every detail", "Couldn’t be worse", "Poor quality",
    "This is useless for me", "Disappointed with the results", "It’s just terrible", "Nothing fits properly", "I absolutely hate it",
    "Terrible design and function", "Totally dissatisfied with this", "I’m upset about this result", "Everything went wrong", "Worst decision ever",
    "Horrible job", "Terrible craftsmanship", "Looks awful", "This brings me frustration", "I’m beyond upset",
    "I hate the effort here", "Such a negative experience", "It’s so badly done", "Low quality", "Very poorly organized",
    "I’m very displeased", "Terrible design", "Everything feels off", "Hated how it turned out", "No attention to detail",
    "Poorly done", "Bad execution", "Everything looks horrible", "I regret choosing this", "So disappointing",
    "Such a bad idea", "Broken work", "Terrible service", "I hate the outcome", "Everything went terribly",
    "Looks even worse than expected", "I’m truly annoyed", "This doesn’t work at all", "Bad performance", "Such a messy design",
    "Everything fails constantly", "It’s an absolute failure", "I feel so negative about this", "It’s just wrong", "This failed my hopes",
    "So messy and clumsy", "A really depressing result", "Simply the worst", "Nothing like I imagined", "It makes me feel terrible",
    "Everything went off-track", "It’s absolutely not worth it", "This is broken", "Pure disaster", "Terrible improvement",
    "Poorly thought out", "This feels so unprofessional", "I hate the complexity", "Everything’s awful", "I can’t stand this",
    "Just horrible overall", "So dull and uninspiring", "Awful from start to finish", "Everything’s just bad", "A very negative result", "Everything feels terrible", "It turned out awful", "I’m frustrated with this", "Terrible experience overall", "Absolutely dreadful result",
    "So disappointing to see this", "I really dislike this", "Nothing works right", "I’m upset about this", "This looks terrible to me",
    "Hate the design here", "Everything feels broken", "So unhappy with the outcome", "It’s just so messy", "Awful idea",
    "I truly dislike this", "Everything went wrong again", "Terrible work", "So embarrassed by the result", "No attention to detail",
    "Such a frustrating experience", "This feels like failure", "Bad timing", "Not what I needed", "Truly disappointing result",
    "Everything turned out badly", "I feel angry", "This gives me stress", "Horrible energy", "Such a dull design",
    "This makes me feel annoyed", "Terrible effort overall", "So much negativity here", "Everything fell apart", "Looks unprofessional and sloppy",
    "I couldn’t be more displeased", "So careless and lazy", "Everything’s confusing", "This is poor work", "Completely missed the point",
    "Such a depressing outcome", "Feels so bad", "Exactly the opposite of what I wanted", "Hate how rough it is", "I’m ashamed of this",
    "Everything is misaligned", "It’s such a failure", "A truly upsetting moment", "Everything feels unbalanced", "Horrible result overall",
    "This is a total mess", "Completely broken", "Super unhappy with this", "It’s below expectations", "Awful color and style",
    "This makes me feel angry", "I hate the simplicity here", "So negative and dull", "Everything looks cheap", "I despise this outcome",
    "Such a meaningless result", "It’s completely wrong", "I hate every detail", "Terrible flow and structure", "Awful example of bad work",
    "Feels so unnatural", "This brings me stress", "Looks rough and unpolished", "I’m mad about this", "A job poorly done",
    "Everything clashes badly", "It’s terribly made", "This has no potential", "Poorly executed plan", "Such an awful surprise",
    "This fills me with regret", "Everything’s disorganized", "Just hate it", "This feels empty", "Such a frustrating result",
    "It’s really disappointing", "This failed every goal", "Completely terrible", "I’m disgusted", "Looks and feels cheap",
    "Everything is designed badly", "So clumsy and awkward", "Horrible presentation", "Absolutely unsatisfying outcome", "Such a pointless idea",
    "Bad vibe and energy", "Totally failed expectations", "It’s nothing like I envisioned", "This gives a bad impression", "Absolutely hate this concept",
    "Feels fake and forced", "Super unimpressive", "It’s all so disorganized", "I hate how it feels", "Everything’s rough and uneven",
    "Pure disaster", "No attention to improvement", "I’m annoyed by the imbalance", "Feels like a mistake", "A bad experience overall"
]

# data preprocessing
def preprocess(text):
    text = text.lower() # convert all text to lowercase
    text = text.translate(str.maketrans("", "", string.punctuation))
    return text

# create a dataset
data = positive_sentences + negative_sentences
labels = [1] * len(positive_sentences) + [0] * len(negative_sentences)

# data preprocessing
data = [preprocess(sentence) for sentence in data]

# create vocab (vocabulary)
all_words = " ".join(data).split()
word_counts = Counter(all_words)
vocab = {word: idx+1 for idx, (word, _ ) in enumerate(word_counts.items())}
vocab["<PAD>"] = 0 # padding, define custom token

# converting data to tensors
max_len = 15
def sentence_to_tensor(sentence, vocab, max_len = 15):
    tokens = sentence.split() # split the sentence into tokens, that is, words
    indices = [vocab.get(word, 0) for word in tokens]
    indices = indices[:max_len]
    indices += [0] * (max_len - len(indices))
    return torch.tensor(indices)

X = torch.stack([sentence_to_tensor(sentence, vocab, max_len) for sentence in data])
y = torch.tensor(labels)

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""# Creating the transformers model"""

class TransformerClass(nn.Module):

    def __init__(self, vocab_size, embedding_dim, num_heads, num_layers, hidden_dim, num_classes):
        super(TransformerClass, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.positional_encoding = nn.Parameter(torch.randn(1, max_len, embedding_dim))
        self.transformer = nn.Transformer(d_model=embedding_dim, # embedding vector size
                                          nhead=num_heads, # title number in the multi-head attention mechanism
                                          num_encoder_layers=num_layers, # transformer encode layer count
                                          dim_feedforward=hidden_dim) # hidden layer size in the encoder

        self.fc = nn.Linear(embedding_dim*max_len, hidden_dim)
        self.out = nn.Linear(hidden_dim, num_classes)
        self.sigmoid = nn.Sigmoid()


    def forward(self, x):
        embedded = self.embedding(x) + self.positional_encoding
        output = self.transformer(embedded, embedded)
        output = output.view(output.size(0), -1)
        output = torch.relu(self.fc(output))
        output = self.out(output)
        output = self.sigmoid(output)
        return output

"""# Training"""

vocab_size = len(vocab)
embedding_dim = 32
num_heads = 4
num_layers = 2
hidden_dim = 64
num_classes = 1 # positive comments and negative comments

model = TransformerClass(vocab_size, embedding_dim, num_heads, num_layers, hidden_dim, num_classes)

# loss ve optimzier
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.0005)

# Training
num_epochs = 30
model.train()# put the model in training mode
for epoch in range(num_epochs):
    optimizer.zero_grad() # reset gradients
    output = model(X_train.long()).squeeze()
    loss = criterion(output, y_train.float())
    loss.backward() # calculate gradients
    optimizer.step()

    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss}")

"""# Test"""

model.eval()
with torch.no_grad():
    y_pred = model(X_test.long()).squeeze()
    y_pred = (y_pred > 0.5).float()

    y_pred_training = model(X_train.long()).squeeze()
    y_pred_training = (y_pred_training > 0.5).float()

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy}")

accuracy_training = accuracy_score(y_train, y_pred_training)
print(f"Training Accuracy: {accuracy_training}")